# Generated by Django 5.0.1 on 2024-01-28 16:15

import django.db.models.deletion
import uuid
import web_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('product_type', models.IntegerField(choices=[(0, 'With Universal Item'), (1, 'With Unique Items')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('file', models.FileField(null=True, upload_to=web_app.models.custom_path)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inner_order', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to=web_app.models.custom_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
