# Generated by Django 5.0.1 on 2024-02-11 09:40

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Инструкция')),
                ('file', models.ImageField(blank=True, null=True, upload_to=web_app.models.custom_path, verbose_name='Файл (опционально)')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, upload_to=web_app.models.custom_path, verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(choices=[(0, 'With Universal Item'), (1, 'With Unique Items')], verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
